### PR TITLE
Breadth closure gives more answers that needed and the Check operator is no needed.

### LINKED ISSUE #69: Breadth closure gives more answers that needed and the Check operator is no needed.
**Describe the bug**
Breadth closure gives more answers that needed and the Check operator is no needed.

### PR DESCRIPTION
**Pull request by johan-smc**
### Summary

- Remove check operator in grammar visitor
- Change Child function check empty answers
- Change Sibling function check the empty answers and don't move
- Change Treepat function return only one response for every call
- Remove filter in the Merge response function
- Fix bug in Implementation tree

### Test Plan
`mvn test`

- Added more test cases.

### Related Issues
close #69

### CODE REVIEW

File: src/main/kotlin/operators/ChildFunction.kt [hunk 1]
```diff
@@ -8,8 +8,12 @@ fun childFunction(
...
     if (fathers.hasMatch) {
         answers = fathers.responses.map {
-            val response = child.invoke(it.lastVisitedSibling?.moveToFirstChild())
-            VisitorFunctionResponseFactory.createMergeResponse(it, response, true)
+            if (it.matches.isEmpty()) {
+                VisitorFunctionResponseFactory.createResponseWithZeroMatches(targetTreeNode, true)
+            } else {
+                val response = child.invoke(it.lastVisitedSibling?.moveToFirstChild())
+                VisitorFunctionResponseFactory.createMergeResponse(it, response, true)
+            }
```
Comment (johan-smc) [inline src/main/kotlin/operators/ChildFunction.kt]: Not continue if are not match in breadth closure.

File: src/main/kotlin/operators/SiblingFunction.kt [hunk 2]
```diff
@@ -8,7 +8,11 @@ fun siblingFunction(
     var answers = emptyList<VisitorFunctionResponse>()
     if (firstAnswer.hasMatch) {
         answers = firstAnswer.responses.map {
-            val response = secondSibling.invoke(it.lastVisitedSibling?.moveToRightSibling())
+            var nextNode = targetTreeNode
+            if (it.matches.isNotEmpty()) {
+                nextNode = it.lastVisitedSibling?.moveToRightSibling()
+            }
+            val response = secondSibling.invoke(nextNode)
```
Comment (johan-smc) [inline src/main/kotlin/operators/SiblingFunction.kt]: If breadth closure is empty don't move to the right.

File: src/main/kotlin/operators/TreepatFunction.kt [hunk 3]
```diff
@@ -4,8 +4,19 @@ fun treepatFunction(expression: VisitorFunction): VisitorFunction = { targetTree
...
+        answers.add(
+            VisitorFunctionResponse(
+                response.responses.filter { it.matches.isNotEmpty() },
+                response.hasMatch
+            )
+        )
         currentNode = currentNode.nextLeftmostPreorderNode()
     }
-    VisitorFunctionResponseFactory.createResponse(answers, targetTreeNode)
+    val allHasMatches = answers.filter { it.hasMatch }.filter { it.responses.isNotEmpty() }.map { it.responses.last() }
```
Comment (johan-smc) [inline src/main/kotlin/operators/TreepatFunction.kt]: Get last valid matches, is the bigger match in breadth closure. Check test case 8 in the breadth close folder.
